<div class="col-sm-12" style="margin: 0px; padding: 0px;">
                    <a href="[field:arcurl /]">
                        <div class="gallery-item">
                            <img src="[field:picname /]" class="img-responsive">
                            <div class="img-caption">
                                <h4>[field:title /]</h4>
                                <p>[field:pubdate function="GetDateMK(@me)"/]</p>
                            </div>
                        </div>
                    </a>
                </div>