<div class="col-sm-3 animated" data-animation="bounceIn" data-delay="[field:global name=autoindex runphp="yes"]@me=@me-1;[/field:global]00" style="text-align: center;">
                <a href="[field:arcurl /]">
                <img src="[field:picname /]" >
                <div class="hgs-content">
                    <h4>[field:title /]</h4>
                    <p>[field:description function=”cn_substr(@me,70)”/]</p>
                    <p style="text-align: right;">---[field:writer /]</p>
                </div>
                </a>
            </div>