<div class="col-sm-4 animated" data-animation="bounceIn" data-delay="[field:global name=autoindex runphp="yes"]@me=@me-1;[/field:global]00">
                <a href="ield:arcurl /]">
                    <div class="walkhi2">
                        <img src="[field:picname /]" class="img-responsive">
                        <h4>[field:title /]</h4>
                        <p>[field:pubdate function="GetDateMK(@me)"/]</p>
                    </div>
                </a>
            </div>