<div class="view-content-left animated" data-animation="bounceIn" data-delay="0">
                    <a href="[field:arcurl /]">
                        <div class="gallery-item">
                            <img src="[field:picname /]" class="img-responsive">
                            <div class="info">
                                <div class="info-con">[field:typelink/]</div>
                            </div>
                        </div>
                    </a>
                    <div class="content1">
                        <h4><a href="[field:arcurl/]">[field:title/]</a></h4>
                        <p>[field:description function="cn_substr(@me,120)"/]</p>
                        <span class="pull-left"><i class="fa fa-clock-o"></i>[field:pubdate function="GetDateMK(@me)"/]</span>
                    </div>
                    <div class="clearfix"></div>
                </div>