<div class="col-sm-8 clear-lr gallery-item animated" data-animation="bounceIn" data-delay="0">
                <a href="[field:arcurl /]">
                    <div class="gallery-item" style="height: 253px; overflow: hidden;">
                        <img src="[field:picname /]" class="img-responsive">
                        <div class="img-caption">
                            <h4>[field:title /]</h4>
                            <p>[field:pubdate function="GetDateMK(@me)"/]</p>
                        </div>
                    </div>
                </a>
            </div>