<div class="col-sm-3 clear-lr animated" data-animation="bounceIn" data-delay="400" style="margin: 0px;">
                <a href="[field:arcurl /]">
                    <div class="gallery-item" >
                        <img src="[field:picname /]" class="img-responsive minheight">
                        <div class="img-caption">
                            <h4>[field:title /]</h4>
                            <p>[field:pubdate function="GetDateMK(@me)"/]</p>
                        </div>
                    </div>
                </a>
            </div>