<div class="col-sm-12" style="margin: 0;padding: 0px;">
                    <a href="[field:arcurl /]">
                    <div class="gallery-item" style="height: 200px; overflow: hidden;">
                        <img src="[field:picname /]" class="img-responsive">
                        <div class="info">
                            <div class="info-con">
                                <h3>[field:title /]</h3>
                                <p>[field:description function="cn_substr(@me,90)"/]</p>
                            </div>
                        </div>
                        <div class="img-caption">
                            <h3>[field:title /]</h3>
                            <p>[field:pubdate function="GetDateMK(@me)"/]</p>
                        </div>
                    </div>
                    </a>                    
                </div>