<?php
$z[0]=Array("global","",1069,1096);
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("global","",1175,1202);
$z[1][4]['name']="cfg_basehost";
$z[2]=Array("global","",1264,1291);
$z[2][4]['name']="cfg_basehost";
$z[3]=Array("global","",1349,1376);
$z[3][4]['name']="cfg_basehost";
$z[4]=Array("global","",1432,1459);
$z[4][4]['name']="cfg_basehost";
$z[5]=Array("global","",1565,1592);
$z[5][4]['name']="cfg_basehost";

?>