<?php
$z[0]=Array("global","",690,717);
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("channel","\r\n                    <li class=\"active_[field:global name=autoindex runphp=\"yes\"]@me=@me+1;[/field:global]\"><a href=\"[field:typeurl /]\">[field:typename /]</a></li>\r\n                    ",756,989);
$z[1][4]['row']="5";
$z[1][4]['type']="top";
$z[2]=Array("global","",1104,1131);
$z[2][4]['name']="cfg_basehost";
$z[3]=Array("type","[field:ID /]",1395,1430);
$z[4]=Array("type","[field:ID /]",1471,1506);
$z[5]=Array("type","[field:ID /]",1553,1588);

?>